### ISSUE TITLE
Connections automatically close when running within a Windows Service

### ISSUE THREAD

**Issue by jchristn** [statianzo/Fleck#127]
Hello, thanks for producing this library, and I hope you don't mind me filing a request here directly rather than trying some other way to contact you.  An implementation one of my coworkers uses can run either interactively or as a Windows service.  The Fleck websocket library works as expected when run interactively (OnOpen, OnMessage, OnClose as expected), however, when run as a Windows service, OnClose gets fired immediately after OnOpen.  

Are there any known issues with using Fleck inside of a Windows service?  Same behavior exists on Chrome 40, IE 11, and Firefox 35.  Thanks!

**Comment by statianzo** [comment]
I'm not sure why behavior would be any different within a windows service. Permissions would be one of my only guesses.

**Comment by jchristn** [comment]
Thank you.  I'll test with a credential set other than 'Local System' to see if it behaves differently and get back to you.

**Comment by jchristn** [comment]
Hi, I tried changing the service to run as the user and also tried administrator, the same behavior is exhibited.  However when I run interactively this does not happen.  Any idea?  Have you tested Fleck with a Windows service?  Thanks!

**Comment by rickparrish** [comment]
I haven't personally, but someone recently contacted me and said they modified my windows forms app to run as a service, and it's working fine for them.

**Comment by statianzo** [comment]
I haven't tried using it as a windows service before. Try setting `FleckLog.LogLevel = LogLeve.Debug` and setting FleckLog.Action to write to a file (or windows event log). That should help give some additional details about what's happening.

**Comment by jchristn** [comment]
May be a dumb question, but I was on 11.1.35 and went to 12.0.38 and neither of them have FleckLog.Loglevel - am I on the wrong version?  LogAction is present, but not Loglevel.

**Comment by statianzo** [comment]
The fully qualified names of them are: `Fleck.LogLevel` (an enum) and `Fleck.FleckLog` (which has `Action` and `Level` properties on it). It's been around since the inception of Fleck, so it will be in there.

**Comment by jchristn** [comment]
Thanks, here's the log output.  It appears it's an issue with one of our subordinate libraries.  Thanks for educating me on enabling debugging, I'll work with the team here to fix.  Thanks!

127.0.0.1 02/20/2015 03:26:59 AM server Debug server fleck (debug message): Client connected from ::ffff:98.207.238.219:60422
127.0.0.1 02/20/2015 03:26:59 AM server Debug server fleck (debug message): 491 bytes read
127.0.0.1 02/20/2015 03:26:59 AM server Debug server fleck (debug message): Building Hybi-14 Response
127.0.0.1 02/20/2015 03:26:59 AM server Debug server fleck (debug message): Sent 129 bytes
127.0.0.1 02/20/2015 03:26:59 AM server Debug server fleck (debug message): 42 bytes read
127.0.0.1 02/20/2015 03:26:59 AM server Debug server fleck (default message): Failed to send. Disconnecting.
127.0.0.1 02/20/2015 03:26:59 AM server Debug server fleck (exception message): System.AggregateException: One or more errors occurred. ---(gt) System.NullReferenceException: Object reference not set to an instance of an object.
   at MyNvFBCH264.setEncodingParameters(MyNvFBCH264* ) in c:\code\paperspace\ps_server (new)\ps_server_dll\ps_server\ps_gridstream\ps_nvfbch264.cpp:line 85
   at MyNvFBCH264.{ctor}(MyNvFBCH264* ) in c:\code\paperspace\ps_server (new)\ps_server_dll\ps_server\ps_gridstream\ps_nvfbch264.cpp:line 14
   at GridStreamWrapper.GridStreamWrapperClass..ctor() in c:\code\paperspace\ps_server (new)\ps_server_dll\ps_server\ps_gridstreamwrapper\ps_gridstreamwrapper.cpp:line 12
   at paperspace.Program.<(gt)c__DisplayClasse.<(gt)c__DisplayClass10.<server_start(gt)b__6() in c:\Code\Paperspace\PS_SERVER (new)\PS_SERVER_SVC\PS_Server_Service\server\server.cs:line 190
   at Fleck.WebSocketConnection.<(gt)c__DisplayClass11.<SendBytes(gt)b__f()
   at Fleck.SocketWrapper.<(gt)c__DisplayClass1e.<Send(gt)b__18(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---(gt) (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at MyNvFBCH264.setEncodingParameters(MyNvFBCH264* ) in c:\code\paperspace\ps_server (new)\ps_server_dll\ps_server\ps_gridstream\ps_nvfbch264.cpp:line 85
   at MyNvFBCH264.{ctor}(MyNvFBCH264* ) in c:\code\paperspace\ps_server (new)\ps_server_dll\ps_server\ps_gridstream\ps_nvfbch264.cpp:line 14
   at GridStreamWrapper.GridStreamWrapperClass..ctor() in c:\code\paperspace\ps_server (new)\ps_server_dll\ps_server\ps_gridstreamwrapper\ps_gridstreamwrapper.cpp:line 12
   at paperspace.Program.<(gt)c__DisplayClasse.<(gt)c__DisplayClass10.<server_start(gt)b__6() in c:\Code\Paperspace\PS_SERVER (new)\PS_SERVER_SVC\PS_Server_Service\server\server.cs:line 190
   at Fleck.WebSocketConnection.<(gt)c__DisplayClass11.<SendBytes(gt)b__f()
   at Fleck.SocketWrapper.<(gt)c__DisplayClass1e.<Send(gt)b__18(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
 One or more errors occurred.
127.0.0.1 02/20/2015 03:26:59 AM server Debug server closing connection from ::ffff:98.207.238.219:60422
127.0.0.1 02/20/2015 03:26:59 AM server Debug server fleck (debug message): Swallowing ObjectDisposedException
127.0.0.1 02/20/2015 03:26:59 AM server Debug server fleck (exception message): System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
