### ISSUE TITLE
[INFO] Message

### ISSUE THREAD

**Issue by Saloed123** [statianzo/Fleck#242]
Hello, time to time i get this exception
```
PM [Info] Failed to send. Disconnecting. System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Unable to write data to the transport connection: An existing connection was f
orcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndWrite(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.EndWrite(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing conne
ction was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndWrite(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.EndWrite(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---
```
Its look like simple info message, but this pause my server on several seconds.
How i can disable this info message, or maybe another way to fix it.

**Comment by Saloed123** [comment]
and this
`9/5/2018 5:53:45 PM [Info] Failed to send. Disconnecting. System.AggregateException: One or more errors occurred. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.EndWrite(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.EndWrite(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---
`

**Comment by Saloed123** [comment]
I use it
```
 private bool IsAlive => connection.IsAvailable;
        private void SendPlainAsync(string message)
        {
            try
            {
                if (IsAlive)
                    connection?.Send(message)?.AttachDefaultExceptionHandler();
            }
            catch (Exception e)
            {
                CloseSession();
            }
        }

 private void CloseSession()
        {
            connection?.Close();
            OnClosed?.Invoke(this, EventArgs.Empty);
        }
```

**Comment by Saloed123** [comment]
```
 public void SetupConnection(IWebSocketConnection socket)
        {
            connection = socket;
            connection.OnClose += CloseSession;
            connection.OnOpen += OnOpen;
            connection.OnMessage += ProcessPlainMessage;
            connection.OnError += exception => { CloseSession(); };
        }
```

**Comment by AdrianBathurst** [comment]
The message `An existing connection was forcibly closed by the remote host` can also be triggered when a client doesn't close the socket connection gracefully, so `OnClose()` may not get triggered. Not uncommon to happen. Ultimately, the connection has gone, so you'll need to remove the connection from your logic.
