### ISSUE TITLE
Certificate chain not working (.pem file)

### ISSUE THREAD

**Issue by abhang-atish** [statianzo/Fleck#272]
I have certificates (`.pem` extension) provided by the VPS certificate resides on the server it self.

`
X509Certificate2 certificate = new X509Certificate2("certificateChain.pem");
                    server.Certificate = certificate;
                    server.EnabledSslProtocols = SslProtocols.Tls12 | SslProtocols.Ssl3 | SslProtocols.Tls11 | SslProtocols.Tls;
`
On trying to connect I'm getting error on server as
`
2019-10-17 05:58:07,783 WARN [24] - Failed to Authenticate
System.AggregateException: One or more errors occurred. ---> System.IO.IOException: The handshake failed due to an unexpected packet format.
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.IOException: The handshake failed due to an unexpected packet format.
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---
`
1. Can i even use `.pem` certificate with Fleck?
2. If yes how do i solve this issue??

**Comment by AdrianBathurst** [comment]
Use .pfx
