### ISSUE TITLE
OnError('Error while reading') not followed by a call to OnClose

### ISSUE THREAD

**Issue by wiz0u** [statianzo/Fleck#282]
I just observed a case where the client of my websocket server disconnected, and this resulted in:
* the OnError event being called with text "Error while reading" and an IOException (with SocketException inner exception)
* followed by a Log Level.Debug "Error while reading"
* and I was never called on OnClose (even though I have an OnClose handler)

Subsequent tries to write a message to the websocket client resulted of course in the warning "Data sent while closing or after close. Ignoring."

As far as I can see in ILSpy, I would have expected Fleck to call Close(1006) and at some point CloseSocket calling my OnClose handler, but it obviously didn't happen...

Note: I'm using Fleck 1.1.0 and my OnError handler only logs the issue and does not try to close the socket.

```
17:59:29.589|ERROR 28|WebSocket| Error while reading
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
17:59:29.589|DEBUG 28|WebSocket| Error while reading
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
17:59:31.074|DEBUG 42|WebSocket| Pushing JSON
17:59:31.558|WARN  42|WebSocket| Data sent while closing or after close. Ignoring.

```

**Comment by wiz0u** [comment]
I believe this could be due to `Close(int code)` checking IsAvailable and Socket.Connected already returning false at this point.
But then this means the user code is not signaled about the socket being closed, unless you expect us to check in OnError about the type of exception transmitted...

**Comment by statianzo** [comment]
There's a lot of discussion around this in #113.

I'd consider triggering OnClose on unclean disconnects to be reasonable behavior.

Taking a glance at [nodejs's sockets](https://github.com/nodejs/node/blob/master/lib/net.js#L664) as prior art, `close` is always called on socket destroy.

I no longer actively develop this project, but do review PRs and cut new releases. So if you or anyone is interested in contributing the functionality, I would bring it in.

**Comment by wiz0u** [comment]
I will see what I can do, but it seems my workplace prevents me from accessing github git server.
