### ISSUE TITLE
在 windows xp 下运行报错

### ISSUE THREAD

**Issue by waleswood** [statianzo/Fleck#296]
```shell
System.Net.Sockets.SocketException (0x80004005): 提供了一个无效的参数。
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at Fleck.WebSocketServer..ctor(String location, Boolean supportDualStack)
```

**Comment by statianzo** [comment]
Try setting supportDualStack to false when creating your WebSocketServer to disable IPv6.
